# Generated by Django 3.2 on 2021-05-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blooddonation',
            fields=[
                ('name', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('age', models.FloatField()),
                ('weight', models.FloatField()),
                ('bloodgroup', models.CharField(max_length=20)),
                ('chk1', models.BooleanField(default=False)),
                ('chk2', models.BooleanField(default=False)),
                ('chk3', models.BooleanField(default=False)),
                ('chk4', models.BooleanField(default=False)),
                ('dat', models.DateField(auto_now=True)),
                ('radio', models.CharField(max_length=150)),
                ('img', models.FileField(upload_to='pic')),
            ],
            options={
                'db_table': 'blooddonation',
            },
        ),
    ]
